### ISSUE TITLE
Thinks an empty space " " is misspelt in some occasions

### ISSUE THREAD

**Issue by mic-max** [tbroadley/spellchecker-cli#100]
![image](https://user-images.githubusercontent.com/15165028/182539482-19750e11-ec51-4e4e-a4ed-03712920f039.png)

It thinks the space before a string like this `:telephone:` is a mistake. I use those strings to indicate emoji's in Jekyll's `jemoji` package. When it prints the line and column number the column number actually lines up with the first letter (at least from VS Code) for all the cases included in my screenshot.

This doesn't happen all the time, I have way more than the 5 emojis seen in my screenshot. So there is something special going on for these in particular.

**Comment by tbroadley** [comment]
Thank you for filing an issue!

I'm having difficulty reproducing this issue on my Windows laptop. I tried running the latest version of Spellchecker with the following arguments:

Source file: https://github.com/mic-max/micmax.pw/blob/master/_posts/2022-01-04-call-visualisation.md
Dictionary: https://github.com/mic-max/micmax.pw/blob/master/dictionary.txt

And didn't see any spelling errors.

Which version of the tool are you using? If it's older than 5.0.0, then perhaps this is related to https://github.com/tbroadley/spellchecker-cli/issues/87. If so, you should be able to fix the issue by upgrading to 5.0.1 or 6.0.2.

**Comment by mic-max** [comment]
Ahh I was using an old version

```
+-- spellchecker-cli@4.10.0
`-- spellchecker@3.7.1
```

Running the command `npm i spellchecker-cli@latest -g` to update to the latest version fixed the issue. Thanks, sorry for the noise!
