### ISSUE TITLE
Add more technology words

### ISSUE THREAD

**Issue by a2937** [tbroadley/spellchecker-cli#104]
Hello I'd like to formally add a whole bunch of technology words such as "JSON", "NoSQL", "Steganography", "RDBMS" in addition to function words like "VARCHAR" , "SUBSTR". I'd also like to append "https" to react.txt as it is the more secure version of the protocol. 

I'd like to start by adding a file called sql.txt to the dictionaries folder featuring words dealing with databases and their functions. And add some more common programming related terms to the main dictionary.txt.

**Comment by tbroadley** [comment]
Hello, thanks for the issue!

I like the idea of having a `dictionaries/base.txt` file that contains the terms you suggested and other software-related words.

`dictionary.txt` in the root directory of this repository is the dictionary that is used when spellchecking this repository. That dictionary should only contain words used in this repository. I wouldn't suggest adding more words to that dictionary.

Also, `dictionaries/react.txt` is a dictionary that contains words from the default README generated by `create-react-app`. Unless "https" now appears in that README, it wouldn't make sense to add "https" to `dictionaries/react.txt`.

**Comment by a2937** [comment]
"https" does not unfortunately appear on that README file.
