### ISSUE TITLE
Test fails on Windows(?)

### ISSUE THREAD

**Issue by tbroadley** [tbroadley/spellchecker-cli#106]
![image](https://user-images.githubusercontent.com/8731922/200371335-f4314d48-3058-4ad7-a5af-3d49e5e9cba4.png)

**Comment by tbroadley** [comment]
@a2937 If you feel like investigating this yourself, please go ahead. Otherwise I can reproduce it locally, so I should be able to debug it.

**Comment by a2937** [comment]
This is the problematic assertion.

https://github.com/tbroadley/spellchecker-cli/blob/0bfe195af57f17c9487315978c2cc8f403d810b9/test/cli-test.ts#L351

For some reason it doesn't recognize that the words wasn't repeated if they're on separate lines.

**Comment by a2937** [comment]
This is the fixture in question. 


https://github.com/tbroadley/spellchecker-cli/blob/master/test/fixtures/repeated-words.md

In GitHub it displays as one line but in reality it's two and what is causing the issue.

**Comment by a2937** [comment]
Guessing this will be closed soon because this got resolved.

 https://github.com/wooorm/parse-latin/commit/ebf6961ab3b961699c498e9416169b5e4d698e27

**Comment by tbroadley** [comment]
Nice, thanks for digging in and filing https://github.com/retextjs/retext-repeated-words/issues/10!
