### ISSUE TITLE
Allow passing HTTP and S3 URLs to `--dictionaries`

### ISSUE THREAD

**Issue by Apkahym** [tbroadley/spellchecker-cli#111]
The reason for this issue is that i work with several projects and i have a dictionary for each one.

But this dictionaries are very similar between to each others, and i need add de same words in all of them.

i think if the dictionary is stored in HTTP GET/POST URL, i can update a single dictionary and reuse it as long as it takes

Another option is an S3 standard, like AWS S3, Digitalocean Spaces o Minio bucket.

Right now i can't develop this topic because i don't have free time... in some free time i'll start doing it if i's not ready yet.

**Comment by tbroadley** [comment]
I think this is a reasonable idea! I would accept a PR that changed the `--dictionaries` argument to accept HTTP and S3 URLs as well as file paths.

**Comment by tbroadley** [comment]
It also seems reasonable to me for each project to download the dictionary using another tool, then call Spellchecker with the `--dictionaries` argument pointing to the path of the downloaded dictionary.

**Comment by Apkahym** [comment]
This is a default feature with a user-scoped dictionary. I solved this with a Git sub-module, but this is a workaround. I'm working on my own version because this project is under-maintained and didn't add many useful features recently. 

Thank you for your feedback

(S3 require more attributes than a single url to work safely)

**Comment by tbroadley** [comment]
I'm going to reopen this because I think it represents a reasonable enhancement to this project.

If you've published your project, or will in the future, please share a link!
