### ISSUE TITLE
Too many misspelling error even if all misspell patterns are mentioned in `--ignore`

### ISSUE THREAD

**Issue by raipc** [tbroadley/spellchecker-cli#28]
```
api/data/series/query.md
  206:8-206:13  warning  Too many misspellings; no further spell suggestions are given  overflow      retext-spell
```

Probably this behavior is caused by default `max` setting set to 30 in `retext-spell`, and `--ignore` feature takes place after `retext-spell` plugin finishes its work.

**Comment by tbroadley** [comment]
Thanks for opening this issue!

If you're experiencing this problem while running the tool on a public GitHub repository, would you mind telling me which one? It would make it easier for me to track down the issue.

**Comment by raipc** [comment]
@tbroadley Thank you for fast response and a good tool! We are using it on https://github.com/axibase/atsd
