### ISSUE TITLE
Comparison with github-spellcheck-cli

### ISSUE THREAD

**Issue by madhavarshney** [tbroadley/spellchecker-cli#35]
Hi there!  This project seems similar to `github-spellcheck-cli`.  The key difference I found is that `spellcheck-cli` is meant for running in a local repository and `github-spellcheck-cli` is for contributing corrections to any repository.  I also found that they use different technologies under-the-hood.  Have you considered merging the two projects or making `github-spellcheck-cli` do the GitHub part and use `spellcheck-cli` for the rest?

Thanks, Madhav.

**Comment by tbroadley** [comment]
Hey! Sounds like a reasonable idea. Another possible solution would be to extract [the spellchecker](https://github.com/tbroadley/spellchecker-cli/blob/master/lib/spellchecker.js) into a common library and use it in both projects.

**Comment by madhavarshney** [comment]
Cool!  Are you interested in using [TypeScript](https://www.typescriptlang.org) for either / both projects?

**Comment by tbroadley** [comment]
Sorry for the slow response. Typescript sounds like a good choice! I do like working with typed languages.

I think it would make the most sense to have a shared package that contains the file search, parsing, and spellchecking logic. Then both `github-spellcheck-cli` and `spellchecker-cli` could use the package and just provide the CLI behaviour. If you agree, and you're interested in spending some time on this, maybe you could create a repository for the shared package? If not, I can probably do that. :slightly_smiling_face:

**Comment by madhavarshney** [comment]
Sure.  Which project should I use as a base?  I'm a little busy, but I'll try to convert the spellchecker portion to TypeScript and then separate it.  Also, if you're going that route, you can also consider using a monorepo for all three packages.

**Comment by tbroadley** [comment]
Nice, thanks! I think it'd be better to base it on `spellchecker-cli`. It's using Remark and Retext (+ plugins) for parsing and spellchecking. I think that's better than the way `github-spellcheck-cli` does it, mainly because it works the same across operating systems.

I don't have strong feelings about a monorepo vs. multiple repos, but I do think I'd like to keep the current `github-spellcheck-cli` repo.
