### ISSUE TITLE
ignore the contents of markdown blockquotes

### ISSUE THREAD

**Issue by hkiang01** [tbroadley/spellchecker-cli#45]
```
> none of this should be spell checked
```

**Comment by tbroadley** [comment]
Blockquotes, right? Or are we talking about code blocks?

If it's the former, I wouldn't be averse to adding a way to configure the tool to ignore the contents of blockquotes.

The latter should already be ignored.

**Comment by hkiang01** [comment]
Block quotes

**Comment by tbroadley** [comment]
I thought about this more and I don't know if it makes sense to add a configuration option for this. It seems like ignoring blockquotes would be a relatively rarely-used feature.
