### ISSUE TITLE
Compatible VSCode extensions

### ISSUE THREAD

**Issue by miffels** [tbroadley/spellchecker-cli#55]
I was wondering, are there any compatible VSCode spell checking extensions that can share the dictionary with this CLI? Would be awesome to have consistent spell checking between VSCode and build scripts. I have found old stuff like `remark-lint`, but that is no longer maintained it seems, and I do not see how it would digest a regex-based dictionary.

**Comment by tbroadley** [comment]
That would be neat! I haven't heard of any compatible extensions unfortunately. I developed the regex-based dictionary specifically for this project, so I think it's unlikely anyone has built an extension that consumes the same format.
