### ISSUE TITLE
Quiet flag isn't quiet

### ISSUE THREAD

**Issue by kf6kjg** [tbroadley/spellchecker-cli#68]
```sh
$ spellchecker -qf 'somefile'

Spellchecking 1 files...


```

Is not my definition of quiet.  I submit that the tool should not print anything, including the whitespace, if -q is specified and the file has no mispelins.

Whether or not it prints all the extra lines and status if there ARE misspellings isn't so much of a concern for me.

Here's my use case:

```sh
nodemon --watch . --ext md --exec "find -iname '*.md' -and -not -path '*/node_modules/*' | parallel spellchecker --no-gitignore -qd .vscode/spellright.dict -f '{}'"
```

Which prints out a TON of lines that say "Spellchecking 1 files...` with lots of whitespace.

Why am I using parallel instead of globbing? It's lots, lots faster.

- 14 seconds across 45 files with parallel: `time find -iname '*.md' -and -not -path '*/node_modules/*' | parallel spellchecker --no-gitignore -qd .vscode/spellright.dict -f '{}'`
- 22 seconds across 45 files with xargs: `time find -iname '*.md' -and -not -path '*/node_modules/*' -print0 | xargs - spellchecker --no-gitignore -qd .vscode/spellright.dict -f '{}'`
- 55 seconds across 5 files with glob: `time spellchecker -qd .vscode/spellright.dict -f '**/*.md'` - Yes this is slower with less files than either of the above - and misses files because they are gitignored. Adding the `--no-gitignore` flag increases the file count to 27000.  Ain't got time for that. :P

**Comment by tbroadley** [comment]
Thanks for the issue! Yeah that definitely seems like a bug. Good catch.

Those performance numbers are interesting too. If you're running the command on a public project, you could link it here - at some point I might take a look at why globbing is so much slower than `xargs`.
