### ISSUE TITLE
Configuration file for command line options

### ISSUE THREAD

**Issue by gadhagod** [tbroadley/spellchecker-cli#71]
I was wondering if there was a file in which I could keep all command line options, similar to the way [Mocha does it](https://github.com/mochajs/mocha/tree/master/example/config). This could be useful in cases where there are a bunch of files to be checked, words to be ignored, and more. Kinda like:

```json
{
  "files": ["src/index.md", "src/test.md"],
  "ignore": ["yeet"],
  "language": "en-GB"
}
```
This way you wouldn't have to keep remembering the files to be checked and other options.

By the way, this tool is super useful! Thanks for making it.

**Comment by tbroadley** [comment]
Thanks for the issue! I'm glad you're finding this tool useful :raised_hands: 

I like your suggestion - currently, the tool doesn't support reading options from a file. The pattern Mocha uses seems like a good one to follow. I'll work on adding support for at least YAML configuration this morning.

**Comment by tbroadley** [comment]
Just merged #72 and released v4.6.0!

**Comment by tbroadley** [comment]
Only YAML is supported for now, but I just opened #73 to track adding support for more file formats.

**Comment by gadhagod** [comment]
Wow, thanks for doing this! I can open a PR making it json(c)-compatible.
