### ISSUE TITLE
How do I use --reports exactly?

### ISSUE THREAD

**Issue by p2635** [tbroadley/spellchecker-cli#78]
I added --reports myreport.txt at the end hoping to get a summary of a spellcheck I did. But I could not find the file in the same directory. Can someone give me an example usage of this command?

**Comment by YenHub** [comment]
Hey @p2635 

There are two types of reports you can use, check the [docs on them here](https://github.com/tbroadley/spellchecker-cli#reports), however, .txt is not a supported report type. 

Basically, you've got either XML or JSON. 

To use JSON, simply do:- 

```bash
spellchecker --files **/*.ts --reports report.json
```

This will output a file called "report.json" at the root of the folder from which you have run `spellchecker` 

Hope this helps! 

YenHub 😎
