### ISSUE TITLE
All plugins running even if told otherwise

### ISSUE THREAD

**Issue by magnoliaceiling** [tbroadley/spellchecker-cli#80]
Might be making a really stupid error here, but anyway... If I specify only using two specific plugins when I run, `retext-repeated-words` still pops up and gives errors—but I don't want it to. I've set it to run with: 
`node_modules/.bin/spellchecker --files '20*/*/*.md' -l 'en-GB' --plugins spell syntax-urls  --no-suggestions -d dictionary.txt -q`

Also tried putting the config into a `spellcheckerrc.json`/`.spellcheckerrc.yml` but get the same results. I saw that all plugins on by default was introduced by #6, but haven't seen anyone else have this issue.

**Comment by tbroadley** [comment]
Thanks for filing this issue! I'm able to reproduce this bug in a test. I'll put up a fix shortly.

**Comment by tbroadley** [comment]
Fixed in 4.8.1!
